version: "3.8"
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: hakan
      MONGO_INITDB_ROOT_PASSWORD: kay1983nar
      MONGO_INITDB_DATABASE: product
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - product-network
  product-api:
    depends_on:
      - mongodb
    image: hakankaynar/product:latest
    ports:
      - 8080:8080
    networks:
      - product-network
networks:
  product-network:
    driver: overlay
    attachable: true
