apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T19:14:38Z
  name: mongo-init-config
  namespace: default
data:
  init.js: |-
    db.createUser(
        {
            user: "product_app",
            pwd: "pr0duc7!",
            roles: [
                {
                    role: "readWrite",
                    db: "product"
                }
            ]
        }
    );
