apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: hakan
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: kay1983nar
            - name: MONGO_INITDB_DATABASE
              value: product
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              subPath: init.js
      volumes:
        - name: init-volume
          configMap:
            name: mongo-init-config