apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    environment: local
    app: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: hakan
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: kay1983nar
        - name: MONGO_INITDB_DATABASE
          value: product
      volumeMounts:
        - name: init-volume
          mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          subPath: init.js
  volumes:
    - name: init-volume
      configMap:
        name: mongo-init-config